num_workers: 8
batch_size: 2
root: data/
data_types:
  - judge_output
  # - detailed_structural_descriptions
  # - structure2chemical_features_relationships
  # - structure2biological_features_relationships
  # - comprehensive_conversations

